sylius_api:
    resource: "@SyliusApiBundle/Resources/config/routing/main.yml"
    prefix: /api

sylius_admin:
    resource: "@SyliusAdminBundle/Resources/config/routing.yml"
    prefix: /admin

sylius_web:
    resource: "@SyliusWebBundle/Resources/config/routing/main.yml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook:
    path: "/login/check-facebook"

twitter:
    path: "/login/check-twitter"

app_shop_partial_product_index_latest_by_taxon_code:
    path: /latest/{code}/{count} # configure a new path that has all the needed variables
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction # you make a call on the Product Controller's index action
        _sylius:
            template: $template
            permission: false
            repository:
                method: findLatestByChannelAndTaxonCode # here use the new repository method
                arguments:
                    - "expr:service('sylius.context.channel').getChannel()"
                    - $code
                    - $count